In [3]:
nat01 = input("국적 코드 입력 : ")
gen01 = input("성별 입력 : ")
noPassengerp01 = input("입국 객수 입력 :")
noPassengerb01 = input("전년 동기 입력 :")

국적 코드 입력 : 1
성별 입력 : 1
입국 객수 입력 :1
전년 동기 입력 :1


In [ ]:
p1 = [nat01, gen01, noPassengerp01, noPassengerb01]
p1

In [4]:
pTot =0
bTot =0
passenger = []
for i in range(0, 6):
	nat01 = input("국적코드 입력 : ")
	gen01 = input("성별입력 : ")
	noPassenger01 =  input("입국 객수 입력 : ")
	noPassenger02 = input("전년 동기 입력 : ")
	p1 = [nat01, gen01, noPassengerp01, noPassengerb01]
	passenger.insert(i,p1)
	pTot += int(noPassengerp01)
	bTot += int(noPassengerb01)

국적코드 입력 : A01
성별입력 : 남성
입국 객수 입력 : 1200
전년 동기 입력 : 500
국적코드 입력 : A02
성별입력 : 여성
입국 객수 입력 : 700
전년 동기 입력 : 400
국적코드 입력 : A03
성별입력 : 남성
입국 객수 입력 : 200
전년 동기 입력 : 300
국적코드 입력 : A04
성별입력 : 남성
입국 객수 입력 : 500
전년 동기 입력 : 500
국적코드 입력 : A05
성별입력 : 여성
입국 객수 입력 : 1200
전년 동기 입력 : 500
국적코드 입력 : A06
성별입력 : 남성
입국 객수 입력 : 700
전년 동기 입력 : 40


In [5]:
p1 = passenger
f = open(".\passenger.txt", 'w')
for i in range(0,6):
    data = p1[i][0]+" "+p1[i][1] +" "+str(p1[i][2]) +" "+str(p1[i][3])+"\n"
    f.write(data)
f.close()

In [7]:
f = open("./travel.csv", 'r')
tra = []
tra2 = []
i = 0
fbTot = 0
fpTot = 0
while True:
    line=f.readline()
    tra.insert(i, line)
    if not line:
        break
#    print(line)
    tra2.insert(i, tra[i].split(","))
    print("%s, %s, %s, %s"%(tra2[i][0], tra2[i][1], tra2[i][2], tra2[i][3]))
    fpTot += int(tra2[i][2])
    fbTot += int(tra2[i][3])
    i+=1
f.close()
print(fpTot)
print(fbTot)

A01,  남성,  106320,  85815

A01,  여성,  191436,  125241

A31,  남성,  319,  299

A31,  여성,  42,  54

A18,  남성,  158912,  124486

A18,  여성,  232943,  163466
689972
499361


In [8]:
print("  국적코드   성별       입국객수     전년동기")
print('-'*50)
for i in range(6):
    print("%-12s%-5s   %10d    %10d"%(tra2[i][0], tra2[i][1], int(tra2[i][2]), int(tra2[i][3])))
    print('-'*50)
print('입국객수 총 합계    %d'%fpTot)
print('전년동기 총 합계    %d'%fbTot)

  국적코드   성별       입국객수     전년동기
--------------------------------------------------
A01          남성         106320         85815
--------------------------------------------------
A01          여성         191436        125241
--------------------------------------------------
A31          남성            319           299
--------------------------------------------------
A31          여성             42            54
--------------------------------------------------
A18          남성         158912        124486
--------------------------------------------------
A18          여성         232943        163466
--------------------------------------------------
입국객수 총 합계    689972
전년동기 총 합계    499361


In [16]:
a = 5
b = 3
sum =lambda a,b:a+b

In [19]:
import numpy as np
np.__version__

'1.19.2'

In [30]:
ar1 = np.array([1,2,3,4,5])
ar1
ar2 = np.array([[10,20,30],[40,50,60]])
ar2
ar4 = np.array([[1,2,3],[4,5,6]])
ar5 = np.array([[0,0,0],[0,0,0]])
ar6 = np.array([[1,2],[3,4],[5,6]])
print(ar2*ar4)
np.dot(ar2,ar6)


[[ 10  40  90]
 [160 250 360]]


array([[220, 280],
       [490, 640]])

In [3]:
import csv

In [4]:
f =open('Incheon.csv')
data = csv.reader(f)
header =next(data)
for row in data :
    print(row)
f.close()

['2021-02-23', '112', '-0.6', '-3', '2.7']
['2021-02-24', '112', '0.9', '-2.6', '6.8']
['2021-02-25', '112', '3.2', '0', '6.2']
['2021-02-26', '112', '7.4', '0.6', '14.8']
['2021-02-27', '112', '9.2', '3.2', '15.5']
['2021-02-28', '112', '7', '3.6', '9.7']
['2021-03-01', '112', '3.9', '-0.2', '7.5']
['2021-03-02', '112', '1.9', '-0.5', '5.6']
['2021-03-03', '112', '3.8', '0.3', '7.7']
['2021-03-04', '112', '7.7', '3.4', '12.5']
['2021-03-05', '112', '8', '3.7', '13.5']
['2021-03-06', '112', '6.7', '4.5', '11.4']
['2021-03-07', '112', '5.5', '3', '10.1']
['2021-03-08', '112', '5.3', '1.8', '10.1']
['2021-03-09', '112', '5.6', '2.2', '10.5']
['2021-03-10', '112', '7', '2.6', '13.6']
['2021-03-11', '112', '8', '3.4', '13.2']
['2021-03-12', '112', '9.7', '7.1', '13.6']
['2021-03-13', '112', '7.8', '4.8', '12.7']
['2021-03-14', '112', '5.7', '4.3', '9.6']
['2021-03-15', '112', '9.2', '4.6', '14']
['2021-03-16', '112', '7.4', '4.2', '11.1']
['2021-03-17', '112', '7.1', '2.6', '12.8']
['2021-